lthrt_contact_contact:
    resource: "@LthrtContactBundle/Controller/ContactController.php"
    type:     annotation

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

lthrt_contact:
    resource: "@LthrtContactBundle/Controller/"
    type:     annotation

lthrt_entity:
    resource: "@LthrtEntityBundle/Resources/config/routing.yml"
    prefix:   /

lthrt_schema_visualizer:
    resource: "@LthrtSchemaVisualizerBundle/Resources/config/routing.yml"
    prefix:   /

lthrt_template:
    resource: "@LthrtTemplateBundle/Resources/config/routing.yml"
    prefix:   /

lthrt_tinker:
    resource: "@LthrtTinkerBundle/Resources/config/routing.yml"
    prefix:   /

lthrt_user:
    resource: "@LthrtUserBundle/Resources/config/routing.yml"
    prefix:   /
