lthrt_tinker:
    resource: "@LthrtTinkerBundle/Resources/config/routing.yml"
    prefix:   /

lthrt_template:
    resource: "@LthrtTemplateBundle/Resources/config/routing.yml"
    prefix:   /

lthrt_entity_json:
    resource: "@LthrtEntityJSONBundle/Resources/config/routing.yml"
    prefix:   /

lthrt_schema_visualizer:
    resource: "@LthrtSchemaVisualizerBundle/Resources/config/routing.yml"
    prefix:   /

lthrt_contact:
    resource: "@LthrtContactBundle/Resources/config/routing.yml"
    prefix:   /
