# lthrt_ccs:
#     resource: "@LthrtCCSBundle/Controller/"
#     type:     annotation
#     prefix:   /

logout:
    path: /logout

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

lthrt_contact:
    resource: "@LthrtContactBundle/Controller/"
    type:     annotation

lthrt_entity:
    resource: "@LthrtEntityBundle/Controller/"
    type:     annotation

lthrt_template:
    resource: "@LthrtTemplateBundle/Resources/config/routing.yml"
    prefix:   /

lthrt_user:
    resource: "@LthrtUserBundle/Controller/"
    type:     annotation