lthrt_json_view:
    resource: "@LthrtJSONViewBundle/Resources/config/routing.yml"
    prefix:   /

lthrt_schema_visualizer:
    resource: "@LthrtSchemaVisualizerBundle/Resources/config/routing.yml"
    prefix:   /

lthrt_contact:
    resource: "@LthrtContactBundle/Resources/config/routing.yml"
    prefix:   /
