# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: ^/admin, roles: ROLE_ADMIN }

    encoders:
        LthrtUserBundle\Entity\User:
            algorithm: bcrypt
        Symfony\Component\Security\Core\User\User: plaintext
    # ...

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern:    ^/
            http_basic: ~
            provider: in_memory
            logout:
                path:   /logout
                target: /

    providers:
        in_memory:
            memory: 
                users:
                    lthrt:
                        password: %lthrt_password%
                        roles: 'ROLE_ADMIN'

        lthrt_user_provider:
            entity:
                class: Lthrt\AppBundle:User
                property: username
                # if you're using multiple entity managers
                # manager_name: customer
