# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/.+, roles: ROLE_USER }

    encoders:
        Lthrt\UserBundle\Entity\User:
            algorithm: bcrypt
        Symfony\Component\Security\Core\User\User: plaintext

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            form_login:
                check_path: /login
                login_path: /login
            logout:
                path:   /logout
                target: /
            pattern:    ^/

    providers:
        chain_provider:
            chain:
                providers: [ lthrt_user_provider ]
        in_memory:
            memory: 
                users:
                    lthrt:
                        password: "%lthrt_password%"
                        roles: 'ROLE_ADMIN'

        lthrt_user_provider:
            entity:
                class: Lthrt\UserBundle\Entity\User
